### ISSUE TITLE
FilterProcessor incorrectly modifies first item of any array it encounters

### ISSUE THREAD

**Issue by biggianteye** [graze/monolog-extensions#29]
Given this test from `tests/unit/src/Graze/Monolog/Processor/FilterProcessorTest.php`

```
public function testProcessorIgnoresArrays()
{
    $processor = new FilterProcessor(["apples", "oranges"], 'YOU CAN\'T HANDLE THE TRUTH');
    $record = [
        'apples' => 'lots',
        'oranges' => [1,2,3]
    ];

    $result = $processor($record);

    $this->assertEquals('YOU CAN\'T HANDLE THE TRUTH', $result['apples']);
    $this->assertInternalType('array', $result['oranges']);
}
```

The problem can be demonstrated by adding this line at the end of the test:

```
$this->assertEquals([1,2,3], $result['oranges']);
```

Running the unit tests gives this failure:

```
1) Graze\Monolog\Processor\FilterProcessorTest::testProcessorIgnoresArrays
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 1
+    0 => 'YOU CAN'T HANDLE THE TRUTH'
     1 => 2
     2 => 3
 )
```

**Comment by h-bragg** [comment]
odd.

So it currently works using the `array_walk_recursive` method which should only modify leaf nodes of an array tree.

> Any key that holds an array will not be passed to the function.
>   - http://php.net/manual/en/function.array-walk-recursive.php

this is suggesting that it is passing in the array, but the key is the parent key...

**Comment by biggianteye** [comment]
Caused by `in_array()` in `filterValue()`.

```
php > echo in_array(1, ['foo', 'bar']) ? "Yes" : "No";
No
php > echo in_array(0, ['foo', 'bar']) ? "Yes" : "No";
Yes
```

Why? Because PHP.

Can be fixed by adding the `strict` parameter. I'll do a PR.

```
php > echo in_array(0, ['foo', 'bar'], true) ? "Yes" : "No";
No
```
